services:
  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "80:8000"
      - "8001:8001"
    volumes:
      - ./kong:/kong/declarative
    depends_on:
      - portofolio
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
        reservations:
          memory: 256m
    restart: unless-stopped

  portofolio:
    build:
      context: ../build_0078a
      dockerfile: Dockerfile
    container_name: portofolio
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=256"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
        reservations:
          memory: 256m
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --url http://kong:8000
    depends_on:
      - kong
    restart: unless-stopped
